/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taskmanager.app.templates;

import javax.swing.*;
import java.awt.Color;
import java.awt.event.*;
import taskmanager.app.entities.*;
/**
 *
 * @author jayng
 */
public class AddTask extends javax.swing.JFrame {
    private User user;
    private HomePage homePage;
    private int selectedTaskId;

    /**
     * Creates new form AddTask
     */
    public AddTask(User user, HomePage homePage, int selectedTaskId) { 
        this.user = user;
        this.homePage = homePage;
        this.selectedTaskId = selectedTaskId;
        initComponents();
        loadTask();
    }

    public AddTask(User user, HomePage homePage) {
        this.user = user;
        this.homePage = homePage;
        this.selectedTaskId = -1;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskTitleLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titleTxtArea = new javax.swing.JTextArea();
        deadLineLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentTxtArea = new javax.swing.JTextArea();
        addBtn = new javax.swing.JButton();
        deadlinePicker = new com.toedter.calendar.JCalendar();
        contentLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Task");

        taskTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taskTitleLbl.setText("Enter title:");

        titleTxtArea.setColumns(20);
        titleTxtArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleTxtArea.setLineWrap(true);
        titleTxtArea.setRows(5);
        titleTxtArea.setToolTipText("");
        jScrollPane1.setViewportView(titleTxtArea);

        deadLineLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deadLineLbl.setText("Enter your deadline:");

        contentTxtArea.setColumns(20);
        contentTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contentTxtArea.setLineWrap(true);
        contentTxtArea.setRows(5);
        contentTxtArea.setToolTipText("");
        jScrollPane2.setViewportView(contentTxtArea);

        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addBtn.setText("Add");
        addBtn.setToolTipText("");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deadlinePicker.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        contentLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contentLbl.setText("Enter Content:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(taskTitleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contentLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deadLineLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(deadlinePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(taskTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentLbl)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deadLineLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deadlinePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        // Task task = new Task();
        if (selectedTaskId != -1)
        {
            try {
                Task task = new Task(titleTxtArea.getText(), contentTxtArea.getText(), deadlinePicker.getDate());
                user.getOwnTasks().set(selectedTaskId, task);
                homePage.updateTaskList();
                this.dispose();
                return;
            }
            catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        try {
            Task task = new Task(titleTxtArea.getText(), contentTxtArea.getText(), deadlinePicker.getDate());
            user.addTask(task);
            homePage.updateTaskList();
            this.dispose();
        }
        catch (IllegalArgumentException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void loadTask() {
        Task task = user.getOwnTasks().get(selectedTaskId);
        titleTxtArea.setText(task.getTitle());
        contentTxtArea.setText(task.getDescription());
        addBtn.setText("Update");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //         new AddTask().setVisible(true);
        //     }
        // });
    }

    // private static void addPlaceholder(JTextField textField, String placeholder) {
    //     textField.setForeground(Color.GRAY);
    //     textField.setText(placeholder);

    //     textField.addFocusListener(new FocusListener() {
    //         @Override
    //         public void focusGained(FocusEvent e) {
    //             if (textField.getText().equals(placeholder)) {
    //                 textField.setText("");
    //                 textField.setForeground(Color.BLACK);
    //             }
    //         }

    //         @Override
    //         public void focusLost(FocusEvent e) {
    //             if (textField.getText().isEmpty()) {
    //                 textField.setForeground(Color.GRAY);
    //                 textField.setText(placeholder);
    //             }
    //         }
    //     });
    // }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel contentLbl;
    private javax.swing.JTextArea contentTxtArea;
    private javax.swing.JLabel deadLineLbl;
    private com.toedter.calendar.JCalendar deadlinePicker;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel taskTitleLbl;
    private javax.swing.JTextArea titleTxtArea;
    // End of variables declaration//GEN-END:variables
}
