/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taskmanager.app.templates;

import java.awt.Color;
import javax.swing.*;
import taskmanager.app.controllers.TaskController;
import taskmanager.app.entities.*;
import taskmanager.app.managers.TaskManager;
import java.awt.event.*;

/**
 *
 * @author jayng
 */
public class HomePage extends javax.swing.JFrame {
    private User user;

    /**
     * Creates new form HomePage
     */
    public HomePage(User user) {
        this.user = user;
        initComponents();
        loadListItem();
        // loadTaskPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        Navigator = new javax.swing.JPanel();
        taskLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaskList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        assignedTaskList = new javax.swing.JList<>();
        rmvTaskBtn = new javax.swing.JButton();
        assignedTaskLbl = new javax.swing.JLabel();
        addTaskBtn = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        TeamDisplay = new javax.swing.JPanel();
        teamMateLbl = new javax.swing.JLabel();
        AddMemBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        companionList = new javax.swing.JList<>();
        removeTeammateBtn = new javax.swing.JButton();
        ObDisplay = new javax.swing.JTabbedPane();
        taskPn = new javax.swing.JPanel();
        TaskName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        finishBtn = new javax.swing.JButton();
        statusLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deadlineLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskTxtArea = new javax.swing.JTextArea();
        Update = new javax.swing.JButton();

        jTextPane1.setText("asdasda");
        jScrollPane4.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TaskManager");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Navigator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        taskLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        taskLbl.setForeground(new java.awt.Color(51, 51, 51));
        taskLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskLbl.setText("Your Tasks");

        TaskList.setBorder(null);
        TaskList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TaskList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TaskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TaskList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TaskListFocusLost(evt);
            }
        });
        TaskList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                TaskListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(TaskList);

        assignedTaskList.setBorder(null);
        assignedTaskList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        assignedTaskList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        assignedTaskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        assignedTaskList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                assignedTaskListFocusLost(evt);
            }
        });
        assignedTaskList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                assignedTaskListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(assignedTaskList);

        rmvTaskBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rmvTaskBtn.setText("Remove Task");
        rmvTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvTaskBtnActionPerformed(evt);
            }
        });

        assignedTaskLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        assignedTaskLbl.setForeground(new java.awt.Color(51, 51, 51));
        assignedTaskLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignedTaskLbl.setText("Assigned Tasks");

        addTaskBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addTaskBtn.setText("Add Task");
        addTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigatorLayout = new javax.swing.GroupLayout(Navigator);
        Navigator.setLayout(NavigatorLayout);
        NavigatorLayout.setHorizontalGroup(
            NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane3)
            .addComponent(assignedTaskLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavigatorLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(addTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(rmvTaskBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        NavigatorLayout.setVerticalGroup(
            NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigatorLayout.createSequentialGroup()
                .addComponent(taskLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rmvTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignedTaskLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LogOutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogOutButton.setText("Log out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        TeamDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        teamMateLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teamMateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamMateLbl.setText("Teammates");

        AddMemBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddMemBtn.setText("Add");
        AddMemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMemBtnActionPerformed(evt);
            }
        });

        companionList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        companionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(companionList);

        removeTeammateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removeTeammateBtn.setText("Remove");
        removeTeammateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTeammateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeamDisplayLayout = new javax.swing.GroupLayout(TeamDisplay);
        TeamDisplay.setLayout(TeamDisplayLayout);
        TeamDisplayLayout.setHorizontalGroup(
            TeamDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teamMateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TeamDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeTeammateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane5)
        );
        TeamDisplayLayout.setVerticalGroup(
            TeamDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamDisplayLayout.createSequentialGroup()
                .addComponent(teamMateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TeamDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeTeammateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        teamMateLbl.getAccessibleContext().setAccessibleDescription("");

        taskPn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TaskName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TaskName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskName.setText("TaskName");

        jLabel1.setText("Status:");

        finishBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        statusLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusLbl.setText("Task Status");

        jLabel3.setText("End at:");

        deadlineLbl.setText("dd/mm/yyyy");

        taskTxtArea.setColumns(20);
        taskTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taskTxtArea.setLineWrap(true);
        taskTxtArea.setRows(5);
        jScrollPane1.setViewportView(taskTxtArea);

        Update.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout taskPnLayout = new javax.swing.GroupLayout(taskPn);
        taskPn.setLayout(taskPnLayout);
        taskPnLayout.setHorizontalGroup(
            taskPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskPnLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deadlineLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addComponent(TaskName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        taskPnLayout.setVerticalGroup(
            taskPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPnLayout.createSequentialGroup()
                .addComponent(TaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taskPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(deadlineLbl)
                    .addComponent(jLabel1)
                    .addComponent(statusLbl)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ObDisplay.addTab("Task", taskPn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Navigator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ObDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TeamDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOutButton)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeamDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ObDisplay)
            .addComponent(Navigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showOptionDialog(
                null, 
                "Are you sure?", 
                "Confirmation", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Yes", "No"},
                "Yes" 
        );

        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
            new LoginForm().setVisible(true);

        } 
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void rmvTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvTaskBtnActionPerformed
        // TODO add your handling code here:
        try {
            Task task = user.getOwnTasks().get(TaskList.getSelectedIndex());
            user.removeTask(task);
            updateTaskList();
            loadTaskPanel(null);
        } catch (IndexOutOfBoundsException e) {}

    }//GEN-LAST:event_rmvTaskBtnActionPerformed

    private void addTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskBtnActionPerformed
        // TODO add your handling code here:
        new AddTask(user, this).setVisible(true);
    }//GEN-LAST:event_addTaskBtnActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        // TODO add your handling code here:
        try {
            Task task = user.getOwnTasks().get(TaskList.getSelectedIndex());
            task.setCompleted(true);
            TaskController.writeTxtFile(task, user, null);
            statusLbl.setText(task.getCompleted());
        } catch (Exception e) {}

    }//GEN-LAST:event_finishBtnActionPerformed

    private void TaskListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_TaskListValueChanged
        // TODO add your handling code here:
        assignedTaskList.clearSelection();
        try {
            Task task = user.getOwnTasks().get(TaskList.getSelectedIndex());
            loadTaskPanel(task);
        } catch (Exception e) {}
    }//GEN-LAST:event_TaskListValueChanged

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try {
            new AddTask(user, this, TaskList.getSelectedIndex()).setVisible(true);;
            loadTaskPanel(null);
        } catch (Exception e) {}
    }//GEN-LAST:event_UpdateActionPerformed

    private void removeTeammateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTeammateBtnActionPerformed
        // TODO add your handling code here:
        try {
            Task task = user.getOwnTasks().get(TaskList.getSelectedIndex());
            User selectedUser = task.getAllCompanions().get(companionList.getSelectedIndex());
            task.removeCompanion(selectedUser);
            selectedUser.removeAssignTask(task);
            updateTeammateList(task);
            TaskController.writeTxtFile(task, user, null);
        } catch (IndexOutOfBoundsException e) {}
        
    }//GEN-LAST:event_removeTeammateBtnActionPerformed

    private void AddMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemBtnActionPerformed
        // TODO add your handling code here:
        try {
            Task task = user.getOwnTasks().get(TaskList.getSelectedIndex());
            new AddTeammate(user, task, this).setVisible(true);
        } catch (Exception e) {}
    }//GEN-LAST:event_AddMemBtnActionPerformed

    private void assignedTaskListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_assignedTaskListValueChanged
        // TODO add your handling code here:
        TaskList.clearSelection();
        try {
            Task task = user.getAssignedTasks().get(assignedTaskList.getSelectedIndex());
            loadTaskPanel(task);
        } catch (Exception e) {}
    }//GEN-LAST:event_assignedTaskListValueChanged

    private void TaskListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TaskListFocusLost
        // TODO add your handling code here:
        // TaskList.clearSelection();
        // loadTaskPanel(null);
    }//GEN-LAST:event_TaskListFocusLost

    private void assignedTaskListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_assignedTaskListFocusLost
        // TODO add your handling code here:
        // assignedTaskList.clearSelection();
        // loadTaskPanel(null);
    }//GEN-LAST:event_assignedTaskListFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //         new HomePage().setVisible(true);
        //     }
        // });
    }
    public void updateTaskList() {
        TaskList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = TaskController.getTaskTitle(user).toArray(new String[0]);

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    public void updateAssignedTaskList() {
        assignedTaskList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = TaskController.getAssignedTaskTitle(user).toArray(new String[0]);

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }

        });
    }

    public void updateTeammateList(Task task) {
        // Task task = user.getOwnTasks().get(TaskList.getSelectedIndex());
        if (task == null)
        {
            companionList.setVisible(false);
            return;
        }
        companionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = TaskController.getTeammate(task).toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        companionList.setVisible(true);

    }
    

    private void loadListItem() {
        updateTaskList();
        updateAssignedTaskList();
        updateTeammateList(null);

    }

    private void loadTaskPanel(Task task) {
        if (task == null) {
            TaskName.setText("");

            statusLbl.setText("");

            taskTxtArea.setEditable(false);
            taskTxtArea.setText("");

            deadlineLbl.setText("");
            updateTeammateList(task);

            return;
        }

        TaskName.setText(task.getTitle());

        statusLbl.setText(task.getCompleted());

        taskTxtArea.setEditable(false);
        taskTxtArea.setText(task.getDescription());

        deadlineLbl.setText(task.getDeadline());
        updateTeammateList(task);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMemBtn;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JPanel Navigator;
    private javax.swing.JTabbedPane ObDisplay;
    private javax.swing.JList<String> TaskList;
    private javax.swing.JLabel TaskName;
    private javax.swing.JPanel TeamDisplay;
    private javax.swing.JButton Update;
    private javax.swing.JButton addTaskBtn;
    private javax.swing.JLabel assignedTaskLbl;
    private javax.swing.JList<String> assignedTaskList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList<String> companionList;
    private javax.swing.JLabel deadlineLbl;
    private javax.swing.JButton finishBtn;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton removeTeammateBtn;
    private javax.swing.JButton rmvTaskBtn;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel taskLbl;
    private javax.swing.JPanel taskPn;
    private javax.swing.JTextArea taskTxtArea;
    private javax.swing.JLabel teamMateLbl;
    // End of variables declaration//GEN-END:variables
}
