/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taskmanager.app.templates;

import java.awt.Color;
import javax.swing.*;
import taskmanager.app.controllers.TaskController;
import taskmanager.app.entities.*;
import taskmanager.app.managers.TaskManager;
import java.awt.event.*;

/**
 *
 * @author jayng
 */
public class HomePage extends javax.swing.JFrame {
    private User user;

    /**
     * Creates new form HomePage
     */
    public HomePage(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Navigator = new javax.swing.JPanel();
        NoteLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TargetList = new javax.swing.JList<>();
        taskLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaskList = new javax.swing.JList<>();
        TargetLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NoteList = new javax.swing.JList<>();
        addTaskBtn = new javax.swing.JButton();
        addNoteBtn = new javax.swing.JButton();
        addTargetBtn = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        UserButton = new javax.swing.JButton();
        TeamDisplay = new javax.swing.JPanel();
        teamMateLbl = new javax.swing.JLabel();
        AddMemBtn = new javax.swing.JButton();
        ObDisplay = new javax.swing.JTabbedPane();
        taskPn = new javax.swing.JPanel();
        TaskName = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TaskTxtPn = new javax.swing.JTextPane();
        TargetPanel = new javax.swing.JPanel();
        TargetName = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TargetTxtPn = new javax.swing.JTextPane();
        NotePanel = new javax.swing.JPanel();
        NoteName = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        NoteTxtPn = new javax.swing.JTextPane();

        jTextPane1.setText("asdasda");
        jScrollPane4.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Navigator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        NoteLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NoteLbl.setForeground(new java.awt.Color(51, 51, 51));
        NoteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoteLbl.setText("Notes");

        TargetList.setBorder(null);
        TargetList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TargetList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TargetList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(TargetList);

        taskLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        taskLbl.setForeground(new java.awt.Color(51, 51, 51));
        taskLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskLbl.setText("Tasks");

        TaskList.setBorder(null);
        TaskList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TaskList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = TaskController.getTaskTitle(user).toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TaskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(TaskList);

        TargetLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TargetLbl.setForeground(new java.awt.Color(51, 51, 51));
        TargetLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TargetLbl.setText("Targets");

        NoteList.setBorder(null);
        NoteList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        NoteList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(NoteList);

        addTaskBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addTaskBtn.setText("Add Task");
        addTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskBtnActionPerformed(evt);
            }
        });

        addNoteBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addNoteBtn.setText("Add Note");
        addNoteBtn.setToolTipText("");
        addNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteBtnActionPerformed(evt);
            }
        });

        addTargetBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addTargetBtn.setText("Add Target");
        addTargetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTargetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigatorLayout = new javax.swing.GroupLayout(Navigator);
        Navigator.setLayout(NavigatorLayout);
        NavigatorLayout.setHorizontalGroup(
            NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NoteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(taskLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane3)
            .addComponent(TargetLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavigatorLayout.createSequentialGroup()
                .addGroup(NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavigatorLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(addTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavigatorLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(addNoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavigatorLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(addTargetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavigatorLayout.setVerticalGroup(
            NavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TargetLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTargetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(NoteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        LogOutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogOutButton.setText("Log out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        UserButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserButton.setText("User");
        UserButton.setToolTipText("");
        UserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButtonActionPerformed(evt);
            }
        });

        TeamDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        teamMateLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teamMateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamMateLbl.setText("Teammates");

        AddMemBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddMemBtn.setText("Add Teammate");
        AddMemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeamDisplayLayout = new javax.swing.GroupLayout(TeamDisplay);
        TeamDisplay.setLayout(TeamDisplayLayout);
        TeamDisplayLayout.setHorizontalGroup(
            TeamDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teamMateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddMemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TeamDisplayLayout.setVerticalGroup(
            TeamDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamDisplayLayout.createSequentialGroup()
                .addComponent(teamMateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddMemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        teamMateLbl.getAccessibleContext().setAccessibleDescription("");

        taskPn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TaskName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TaskName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskName.setText("TaskName");

        jScrollPane5.setViewportView(TaskTxtPn);

        javax.swing.GroupLayout taskPnLayout = new javax.swing.GroupLayout(taskPn);
        taskPn.setLayout(taskPnLayout);
        taskPnLayout.setHorizontalGroup(
            taskPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addComponent(TaskName, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        taskPnLayout.setVerticalGroup(
            taskPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPnLayout.createSequentialGroup()
                .addComponent(TaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ObDisplay.addTab("Task", taskPn);

        TargetPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TargetName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TargetName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TargetName.setText("TargetName");

        jScrollPane6.setViewportView(TargetTxtPn);

        javax.swing.GroupLayout TargetPanelLayout = new javax.swing.GroupLayout(TargetPanel);
        TargetPanel.setLayout(TargetPanelLayout);
        TargetPanelLayout.setHorizontalGroup(
            TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TargetName, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );
        TargetPanelLayout.setVerticalGroup(
            TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TargetPanelLayout.createSequentialGroup()
                .addComponent(TargetName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );

        ObDisplay.addTab("Target", TargetPanel);

        NotePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NoteName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        NoteName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoteName.setText("NoteName");

        jScrollPane7.setViewportView(NoteTxtPn);

        javax.swing.GroupLayout NotePanelLayout = new javax.swing.GroupLayout(NotePanel);
        NotePanel.setLayout(NotePanelLayout);
        NotePanelLayout.setHorizontalGroup(
            NotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NoteName, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
            .addComponent(jScrollPane7)
        );
        NotePanelLayout.setVerticalGroup(
            NotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotePanelLayout.createSequentialGroup()
                .addComponent(NoteName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
        );

        ObDisplay.addTab("Note", NotePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Navigator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ObDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogOutButton)
                        .addContainerGap())
                    .addComponent(TeamDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogOutButton)
                    .addComponent(UserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeamDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ObDisplay)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserButtonActionPerformed

    private void addTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addTaskBtnActionPerformed

    private void addNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNoteBtnActionPerformed

    private void addTargetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTargetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTargetBtnActionPerformed

    private void AddMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //         new HomePage().setVisible(true);
        //     }
        // });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMemBtn;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JPanel Navigator;
    private javax.swing.JLabel NoteLbl;
    private javax.swing.JList<String> NoteList;
    private javax.swing.JLabel NoteName;
    private javax.swing.JPanel NotePanel;
    private javax.swing.JTextPane NoteTxtPn;
    private javax.swing.JTabbedPane ObDisplay;
    private javax.swing.JLabel TargetLbl;
    private javax.swing.JList<String> TargetList;
    private javax.swing.JLabel TargetName;
    private javax.swing.JPanel TargetPanel;
    private javax.swing.JTextPane TargetTxtPn;
    private javax.swing.JList<String> TaskList;
    private javax.swing.JLabel TaskName;
    private javax.swing.JTextPane TaskTxtPn;
    private javax.swing.JPanel TeamDisplay;
    private javax.swing.JButton UserButton;
    private javax.swing.JButton addNoteBtn;
    private javax.swing.JButton addTargetBtn;
    private javax.swing.JButton addTaskBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel taskLbl;
    private javax.swing.JPanel taskPn;
    private javax.swing.JLabel teamMateLbl;
    // End of variables declaration//GEN-END:variables
}
